name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: trent0921
          password: ${{ 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 }}
          registry: docker.pkg.github.com
          repository: trent0921/publish-packages/game
          tag_with_sha: true
